/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkPublicKey {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CkPublicKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkPublicKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkPublicKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkPublicKey() {
    this(chilkatJNI.new_CkPublicKey(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkPublicKey_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkPublicKey_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkPublicKey_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkPublicKey_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkPublicKey_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkPublicKey_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkPublicKey_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkPublicKey_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkPublicKey_lastErrorXml(swigCPtr, this);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkPublicKey_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkPublicKey_version(swigCPtr, this);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkPublicKey_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkPublicKey_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkPublicKey_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkPublicKey_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkPublicKey_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkPublicKey_SaveLastError(swigCPtr, this, path);
  }

  public boolean GetOpenSslDer(CkByteData outData) {
    return chilkatJNI.CkPublicKey_GetOpenSslDer(swigCPtr, this, CkByteData.getCPtr(outData), outData);
  }

  public boolean GetOpenSslPem(CkString outStr) {
    return chilkatJNI.CkPublicKey_GetOpenSslPem(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String getOpenSslPem() {
    return chilkatJNI.CkPublicKey_getOpenSslPem(swigCPtr, this);
  }

  public String openSslPem() {
    return chilkatJNI.CkPublicKey_openSslPem(swigCPtr, this);
  }

  public boolean GetRsaDer(CkByteData outData) {
    return chilkatJNI.CkPublicKey_GetRsaDer(swigCPtr, this, CkByteData.getCPtr(outData), outData);
  }

  public boolean GetXml(CkString outStr) {
    return chilkatJNI.CkPublicKey_GetXml(swigCPtr, this, CkString.getCPtr(outStr), outStr);
  }

  public String getXml() {
    return chilkatJNI.CkPublicKey_getXml(swigCPtr, this);
  }

  public String xml() {
    return chilkatJNI.CkPublicKey_xml(swigCPtr, this);
  }

  public boolean LoadOpenSslDer(CkByteData data) {
    return chilkatJNI.CkPublicKey_LoadOpenSslDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadOpenSslDerFile(String path) {
    return chilkatJNI.CkPublicKey_LoadOpenSslDerFile(swigCPtr, this, path);
  }

  public boolean LoadOpenSslPem(String str) {
    return chilkatJNI.CkPublicKey_LoadOpenSslPem(swigCPtr, this, str);
  }

  public boolean LoadOpenSslPemFile(String path) {
    return chilkatJNI.CkPublicKey_LoadOpenSslPemFile(swigCPtr, this, path);
  }

  public boolean LoadPkcs1Pem(String str) {
    return chilkatJNI.CkPublicKey_LoadPkcs1Pem(swigCPtr, this, str);
  }

  public boolean LoadRsaDer(CkByteData data) {
    return chilkatJNI.CkPublicKey_LoadRsaDer(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadRsaDerFile(String path) {
    return chilkatJNI.CkPublicKey_LoadRsaDerFile(swigCPtr, this, path);
  }

  public boolean LoadXml(String xml) {
    return chilkatJNI.CkPublicKey_LoadXml(swigCPtr, this, xml);
  }

  public boolean LoadXmlFile(String path) {
    return chilkatJNI.CkPublicKey_LoadXmlFile(swigCPtr, this, path);
  }

  public boolean SaveOpenSslDerFile(String path) {
    return chilkatJNI.CkPublicKey_SaveOpenSslDerFile(swigCPtr, this, path);
  }

  public boolean SaveOpenSslPemFile(String path) {
    return chilkatJNI.CkPublicKey_SaveOpenSslPemFile(swigCPtr, this, path);
  }

  public boolean SaveRsaDerFile(String path) {
    return chilkatJNI.CkPublicKey_SaveRsaDerFile(swigCPtr, this, path);
  }

  public boolean SaveXmlFile(String path) {
    return chilkatJNI.CkPublicKey_SaveXmlFile(swigCPtr, this, path);
  }

}
