/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkTrustedRoots {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CkTrustedRoots(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkTrustedRoots obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkTrustedRoots(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkTrustedRoots() {
    this(chilkatJNI.new_CkTrustedRoots(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkTrustedRoots_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkTrustedRoots_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkTrustedRoots_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkTrustedRoots_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkTrustedRoots_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkTrustedRoots_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkTrustedRoots_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkTrustedRoots_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkTrustedRoots_lastErrorXml(swigCPtr, this);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkTrustedRoots_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkTrustedRoots_version(swigCPtr, this);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkTrustedRoots_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkTrustedRoots_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkTrustedRoots_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkTrustedRoots_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkTrustedRoots_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkTrustedRoots_SaveLastError(swigCPtr, this, path);
  }

  public int get_NumCerts() {
    return chilkatJNI.CkTrustedRoots_get_NumCerts(swigCPtr, this);
  }

  public boolean get_TrustSystemCaRoots() {
    return chilkatJNI.CkTrustedRoots_get_TrustSystemCaRoots(swigCPtr, this);
  }

  public void put_TrustSystemCaRoots(boolean newVal) {
    chilkatJNI.CkTrustedRoots_put_TrustSystemCaRoots(swigCPtr, this, newVal);
  }

  public boolean LoadCaCertsPem(String path) {
    return chilkatJNI.CkTrustedRoots_LoadCaCertsPem(swigCPtr, this, path);
  }

  public CkCert GetCert(int index) {
    long cPtr = chilkatJNI.CkTrustedRoots_GetCert(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CkCert(cPtr, true);
  }

  public boolean Activate() {
    return chilkatJNI.CkTrustedRoots_Activate(swigCPtr, this);
  }

  public boolean Deactivate() {
    return chilkatJNI.CkTrustedRoots_Deactivate(swigCPtr, this);
  }

  public boolean AddCert(CkCert cert) {
    return chilkatJNI.CkTrustedRoots_AddCert(swigCPtr, this, CkCert.getCPtr(cert), cert);
  }

}
